Add clang-format style checks to CI config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,7 +20,35 @@ commands:
           command: |
             echo "export PATH=$PATH:<<parameters.prefix>>/bin" >> $BASH_ENV
 
+  clang-format-style-check:
+    description: Compare changes against the clang-format style sheet
+    steps:
+      - run:
+          name: Install clang-tools
+          command: |
+            conda install --channel conda-forge clang-tools
+      - run:
+          name: Check C++ style
+          command: |
+            result=$(git clang-format main --diff --quiet)
+            if [ -n "$result" ]; then
+              echo "clang-format check passed"
+            else
+              echo "clang-format check failed"
+              echo
+              echo -e $result
+              exit 1
+            fi
+
 jobs:
+  style-checks:
+    docker:
+      - image: cimg/base:stable
+    steps:
+      - install-miniconda
+      - checkout
+      - clang-format-style-check
+
   build-and-test:
     parameters:
       cmake-preset:
@@ -56,5 +84,6 @@ jobs:
 workflows:
   pr-pipeline:
     jobs:
+      - style-checks
       - build-and-test:
           cmake-preset: ninja-release
